### ISSUE TITLE
mapper.map could contain Mapper class for readability

### ISSUE THREAD

**Issue by maquessime** [amgohan/zebra#1]
The map method of a mapper should take the mapper class as parameter for readability. Otherwise, it can be hard to quickly know which mapper is really used.

Here is an example :

```
User user = mapper.map(userDto, User.class,UserMapper.class);
```

If you could remove the destination class too and fetch from the Mapper class that would be nice.

**Comment by amgohan** [comment]
this enhancement was added to 1.1.0 of zebra lib.

Now you can do : User user = mapper.straightMap(userDto, UserMapper.class);
